POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklsdmVVIiwiaWQiOiI2NGI1MTgwMDJiMThhNWEzMDRmZWU4NjYiLCJpYXQiOjE2ODk1OTA2NDcsImV4cCI6MTY4OTU5NDI0N30.sgzxXv0Qv4cLz4dieB7WXfge2Llq25VwvGtXlg5NMTg

{
    "title": "Thing I did not know before",
    "author": "Hien Nguyen",
    "url": "google.com",
    "likes": 65436
}

### 
PUT http://localhost:3003/api/blogs/646badb62454f74b4d28c838
content-type: application/json

{
    "title": "ChatGPT is taking over the world",
    "author": "OpenAI",
    "url": "openAI.com",
    "likes": 5030,
    "creator": "646b9fce6d298d91e47c9cb6",
    "id": "646badb62454f74b4d28c838"
}

#CREATE USER
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hienthi",
    "name": "hehe",
    "password": "hieng134"

}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "IlveU",
    "name": "I And Your",
    "password": "hahah123"

}

#LOGIN
###
POST http://localhost:3003/api/login 
Content-Type: application/json

{
    "username": "IlveU",
    "password": "hahah123"
}

###
POST http://localhost:3003/api/blogs/64b51b29c1f0f366013f50c8/comments
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhpZW50aGkiLCJpZCI6IjY0NmJiMmMxZWE4M2M4ZTZmMGY2YTY4ZCIsImlhdCI6MTY4OTU4NzY1NiwiZXhwIjoxNjg5NTkxMjU2fQ.wukDc_cNf-I_Gh3g8uGZ7NNtHgSHROTAzZmUuc41W_s

{
    "content": "These are the best"
}
